### ISSUE TITLE
`curl` command not found

### ISSUE THREAD

**Issue by michimussato** [ynput/ayon-docker#34]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
`docker-compose` server health check fails.

## Expected Behavior
`docker-compose` server health check succeeds.

### Additional context:

```
  server:
    image: ynput/ayon:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/info"]
      interval: 10s
      timeout: 2s
      retries: 3
```

But:
`ynput/ayon:latest` does not provide `curl`:

```
root@ayon-server:/backend# curl
bash: curl: command not found
```

An alternate solution (or temporary override) could be:
```
timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5000' || exit 1
```
from https://github.com/dart-lang/dart-docker/issues/58#issuecomment-1086975460
(But this would not be a fix for the bug)

Cheers!

### Relevant log output:

```shell

```
